### ISSUE TITLE
性能参数

### ISSUE THREAD

**Issue by Shapaper233** [hv0905/NekoImageGallery#29]
请问一般来说内存占用多少，cpu占用多少
随着图片数量的增加内存会越来越多吗？
具体大概会有多少呢

**Comment by hv0905** [comment]
在我自己的部署环境中（CPU推理模式，包含30000+张图片），服务器空闲时的内存占用约为3.2G（如下图所示）。

![image](https://github.com/hv0905/NekoImageGallery/assets/29349119/d74f52bf-e01c-43ad-84f8-ac8248b79b4b)

Qdrant数据库占用约1G内存。

![image](https://github.com/hv0905/NekoImageGallery/assets/29349119/a87661ea-60f3-4636-a2cd-f6a686545b75)

- 在服务器空闲时，内存中主要存储的是CLIP与BERT模型的权重文件，因此内存占用不会随图片数量增加而上升。
- 当索引队列中存在大量待上传图片时，内存占用可能会增加，但一般不会超过8G，并且在队列中的所有图片完成索引后，内存会被释放。

关于CPU占用，服务器空闲时基本上没有CPU占用。在进行图片索引时，PyTorch会根据可用的CPU线程数进行推理。因此，除非服务器正在大量索引图片或处理大量的img2img搜索请求，否则CPU占用不会很高。搜索速度作为参考，使用`i5-12490F`, 文搜图大概0.1s/req, 图搜图大概0.7s/req

因此，我建议在生产部署时，至少需要4G内存并设置4G以上的交换空间(swap)，推荐使用8GB或以上的内存（并根据需要设置适当的swap）。CPU配置可以根据需求选择，性能越好的CPU可以提供更快的搜索响应速度和图片索引速度（也可以使用GPU服务器，性能最佳）。

**Comment by Shapaper233** [comment]
请问我使用QQ插件如何上传图片呢？
按照我的理解是不是有地方可以上传图片，并且上传后他会自动处理后保存数据库

**Comment by hv0905** [comment]
目前LiteLoaderQQNT插件暂时不支持图片上传，有下面几种方式可以上传：

- 去催更 LiteLoaderQQNT插件🐶 （ cc @pk5ls20 )
- 在启用Admin API的情况下，使用[NekoImageGallery.App](https://github.com/hv0905/NekoImageGallery.App)的上传页面上传。（推荐）
- 使用本地索引功能（运行`python main.py --local-index <你的图片目录>`进行图片索引，然后使用`python main.py --local-create-thumbnail` 创建缩略图。）
- 如果你有开发经验，可以通过手动调用API的方式上传，这种方式比较适合接入到你自己的爬虫等项目中。

**Comment by Shapaper233** [comment]
有API文档吗？

**Comment by hv0905** [comment]
如果你的后端已经部署好了，直接访问`/docs`即可查看API文档。
参考： https://fastapi.tiangolo.com/tutorial/first-steps/#interactive-api-docs

**Comment by Shapaper233** [comment]
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/d688beae-d5a3-4b64-93a7-410b1cb2cbb3)
没有upload啊😂

**Comment by hv0905** [comment]
> ![image](https://private-user-images.githubusercontent.com/157946924/333777157-d688beae-d5a3-4b64-93a7-410b1cb2cbb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTg2MzEsIm5iZiI6MTcxNjYxODMzMSwicGF0aCI6Ii8xNTc5NDY5MjQvMzMzNzc3MTU3LWQ2ODhiZWFlLWQ1YTMtNGI2NC05M2E3LTQxMGIxY2IyY2JiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwNjI1MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODMxOGM1NGZhYjc5ZmJiMTcxMjMxZTk3MDUwMDFkZDc0ZTA1ZDkzNzMzM2E4ZGJmN2U2MWRiODgxYzZjMGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NiBqUlE2Uqj0RV-Pjl5Q4DSFxe1nWlOOHS_X2l-bkQ0) 没有upload啊😂

你没启用Admin API，设置`APP_ADMIN_API_ENABLE=True`并设置`APP_ADMIN_TOKEN=<你的管理密码>`。
由于安全原因Admin API是默认关闭的。

**Comment by Shapaper233** [comment]
我试试哈
这几个项目关系刚开始没梳理清，一头雾水啊哈哈😂

**Comment by Shapaper233** [comment]
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/ae33c7ff-a2a4-4cf4-911e-1a447cd417fe)
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/e0d221cf-f89e-4d5d-a228-ae9c1ed6282e)
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/11fa3e1f-ccff-4723-abf8-68f97bcc3f6e)
直接打开可以，到qq中就不行了，请问是我上传姿势不正确还是插件问题

**Comment by Shapaper233** [comment]
上传时候填写密钥了

**Comment by Shapaper233** [comment]
明白了，插件地方多打了一个/
他的地址后面**不能有/**
如http://baidu.com **/**
