### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by Shapaper233** [hv0905/NekoImageGallery#30]
我使用docker-compose脚本运行了这个项目
没有做其他操作
用ntqq插件连接不上：
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/2eb44e69-df14-4fde-9dd3-b1b5d20f8097)

**Comment by Shapaper233** [comment]
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/5c9c2b99-1a4c-4acf-b09e-07d113a2aaec)
开启访问后确实可以访问了但是弹出这个

**Comment by hv0905** [comment]
试试直接使用浏览器访问api地址?
如果后端没有问题的话应该会有类似如下的输出：
![image](https://github.com/hv0905/NekoImageGallery/assets/29349119/7ad80cbf-2bb7-4c6b-8233-0eb62d6a8842)

**Comment by Shapaper233** [comment]
![image](https://github.com/hv0905/NekoImageGallery/assets/157946924/3c0627bd-9556-407c-bb64-f9b15b09da99)

**Comment by Shapaper233** [comment]
有没有可能是因为没有图片的缘故？
话说qq插件支持上传表情吗
如何才能上传呢

**Comment by hv0905** [comment]
参考https://github.com/hv0905/NekoImageGallery/issues/29#issuecomment-2130878080
如果你是docker部署的话，建议使用NekoImageGallery.App上传

**Comment by pk5ls20** [comment]
> 有没有可能是因为没有图片的缘故？
> 话说qq插件支持上传表情吗
> 如何才能上传呢

qq插件目前还不支持
